name: packbot

on:
  push:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{github.event_name}}

    - uses: actions/checkout@v2

    - name: Use Node 15
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: Dependencies Cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node-modules-${{hashFiles('package-lock.json')}}
        restore-keys: |
          node-modules-

    - name: Install Dependencies
      run: npm install

    - name: Test
      run: npm run test
      env:
        CI: true

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.event_name == 'release'
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Use Node 15
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: '15.x'

  #   - name: Dependencies Cache
  #     uses: actions/cache@v1
  #     with:
  #       path: node_modules
  #       key: node-modules-${{hashFiles('package-lock.json')}}
  #       restore-keys: |
  #         node-modules-

  #   - name: Install Dependencies
  #     run: npm install

  #   - name: Publish
  #     run: npm run pack:publish
  #     env:
  #       CI: true


